dp/dp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sort_cgpa.urls')),
    path('admin/', admin.site.urls),
]

dp/sort_cgpa/urls.py
from django.urls import path
from . import views

app_name = 'sort_cgpa'

urlpatterns = [
    path('', views.upload_file, name="sort_cgpa"),
]

dp/sort_cgpa/models.py
from django.db import models

# Create your models here.

dp/sort_cgpa/forms.py
from django import forms

class UploadCSVFileForm(forms.Form):
    cgpa_file = forms.FileField()
    teacher_list_file = forms.FileField()

dp/sort_cgpa/views.py
import tempfile
from django.shortcuts import render
from .forms import UploadCSVFileForm
import pandas as pd
import os
from itertools import zip_longest
# Create your views here.

from pprint import pprint

def handle_uploaded_file(f):
    with tempfile.NamedTemporaryFile(delete=False) as fp:
        for chunk in f.chunks():
            fp.write(chunk)
        fp.flush()
        return fp.name
    
    return None

def upload_file(request):
    if request.method == 'POST':
        form = UploadCSVFileForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                # get the uploaded files
                cgpa_file = handle_uploaded_file(request.FILES['cgpa_file'])
                teacher_list_file = handle_uploaded_file(request.FILES['teacher_list_file'])

                # cread csv into pandas
                cgpas = pd.read_csv(cgpa_file)
                teachers = pd.read_csv(teacher_list_file)

                # sort by CGPA column
                sorted_cgpa = cgpas.sort_values(by=["CGPA"], ascending=False, ignore_index=True)

                # add teacher for each roll
                cgpaNteacher = assign_teachers(sorted_cgpa["Roll"].tolist(), teachers["Teachers"].tolist())

                # convert to html for the web
                html_table = cgpaNteacher.to_html(index=False)

                # convert to csv for downloading
                csv_content = cgpaNteacher.to_csv(index=False)

                # the next form
                form = UploadCSVFileForm()

                # delete temporary files created by handle_uploaded_file
                os.unlink(cgpa_file)
                os.unlink(teacher_list_file)

                #return response
                return render(request, 'upload_csv.html', {'form': form, 'csv_content': csv_content, 'html_table': html_table})
            except:
                return render(request, 'upload_csv.html', {'message': 'Incorrect input file'})

    form = UploadCSVFileForm()
    return render(request, 'upload_csv.html', {'form': form})

def assign_teachers(rolls, teachers):
    teacher_length = len(teachers)

    # slice the list according to teacher list length
    sliced_rolls = []
    while len(rolls) > 0:
        sliced_rolls.append(list(rolls[:teacher_length]))
        rolls = rolls[teacher_length:]

    # transpose the list
    allocated_rolls = []
    for sliced_roll in zip_longest(*sliced_rolls, fillvalue=None):
        l = [x for x in list(sliced_roll) if x is not None]
        allocated_rolls.append(l)

    df = pd.DataFrame(allocated_rolls)

    df["Supervisor"] = pd.Series(teachers)
    df.fillna('', inplace=True)

    # n_teachers = teachers
    # df_len = len(df.index)

    # # make the teacher list same as the size of the data frame append the same list multiple times
    # while n_teachers.size <= df_len:
    #     n_teachers = pd.concat([n_teachers, teachers], ignore_index=True)

    # # create new column in the dataframe

    # df["Teacher"] = n_teachers
    
    # df = df.groupby(["Teacher"]).agg({"Roll": lambda x: x.tolist()}).reset_index()

    return df

dp/sort_cgpa/templates/result_csv.html
<html>

<body>
    {{ html_table }}
</body>
</html>

dp/sort_cgpa/templates/upload_csv.html
<html>

<head>
<style>
    html, body {
        display: flex;
        justify-content: center;
        
        }
form input {
    display: block;
    margin: 0.3rem 0;
    
}

input[type=file]::file-selector-button {
    color: #fff!important;
    background-color: #00aba9;
    border: none;
    padding: 8px 16px;
    vertical-align: middle;
    overflow: hidden;
    text-decoration: none;
    text-align: center;
    cursor: pointer;
    white-space: nowrap;
}
input[type=submit], .download_csv {
    width: fit-content;
    margin-top: 1rem;
    color: #fff!important;
    background-color: #2196F3!important;
    border: none;
    padding: 8px 16px;
    vertical-align: middle;
    overflow: hidden;
    text-decoration: none;
    text-align: center;
    cursor: pointer;
    white-space: nowrap;
}

.output_table table {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

.output_table td, .output_table th {
  border: 1px solid #ddd;
  padding: 8px;
}

.output_table tr:nth-child(even){background-color: #f2f2f2;}

.output_table tr:hover {
    background-color: #647687;
    color: #fff;
}

.output_table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #00aba9;
  color: white;
}
</style>
</head>
</html>


{% if form %}
<form action="{% url 'sort_cgpa:sort_cgpa' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endif %}

{% if message %}
    {{ message }}
{% endif %}


{% if csv_content %}
<p class="download_csv" onclick="download_csv_file()">Download CSV File</p>

<script>
    function download_csv_file() {
        var csv_c = `{{ csv_content }}`;
        download("Project Distributor File.csv", csv_c);
    }
    function download(filename, text) {
      var element = document.createElement('a');
      element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
      element.setAttribute('download', filename);
    
      element.style.display = 'none';
      document.body.appendChild(element);
    
      element.click();
    
      document.body.removeChild(element);
    }
</script>
{% endif %}

{% if html_table %}
<div class="output_table" id="output_table">
    {% autoescape off %}
        {{ html_table }}
    {% endautoescape %}
</div>
{% endif %}